#!/bin/bash
# This script generates a .rosinstall file for our source dependencies.
# The .rosinstall file should be kept under version control.
rosinstall_generator ros_comm rosserial rosserial_arduino usb_cam --rosdistro indigo --deps --wet-only --exclude roslisp --tar > openag_brain_ros_indigo_deps_wet.rosinstall