#!/usr/bin/env python
import argparse
from couchdb import Server

from openag_brain import args
from openag_brain.commands import init_db

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="""
Initialize the CouchDB server by setting some configuration parameters given
in the `couchdb.ini` file, creating the necessary databases, and pushing design
documents to them.
    """)
    args.add_db_server_arg(parser)
    args.add_hostname_arg(parser)
    vals = parser.parse_args()
    server = Server(vals.db_server)
    init_db(server, vals.hostname)
