#!/bin/bash
# This script sets up a developer workspace to build openag_brain and its
# dependencies from source.
#
# - Adds ROS package manager source
# - Installs ROS tools for boostrapping install
# - Creates a catkin_workspace
#
# Adapted from these instructions:
# http://wiki.ros.org/ROSberryPi/Installing%20ROS%20Indigo%20on%20Raspberry%20Pi
set -e

# Tell apt to read from the ROS package repository
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu jessie main" > /etc/apt/sources.list.d/ros-latest.list'
wget https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -O - | sudo apt-key add -

# Update apt
sudo apt-get update
sudo apt-get -y upgrade

# Install pip and couchdb (couchdb is not available via rosdep -- see below)
sudo apt-get install -y python-pip couchdb
# Install bootstrapping dependencies
sudo pip install rosdep rosinstall_generator wstool

# Initialize rosdep
if [ -f /etc/ros/rosdep/sources.list.d/20-default.list ];
    then sudo rm /etc/ros/rosdep/sources.list.d/20-default.list
fi
sudo rosdep init
rosdep update

# Create a service
sudo cp ./run.sh /opt/openag_run.sh
sudo cp ./openag.service /lib/systemd/system/openag.service

# Create a catkin workspace
mkdir -p ~/catkin_ws

# Set up ROS and dependencies in workspace with .rosinstall file.
# http://wiki.ros.org/wstool
# http://wiki.ros.org/rosinstall
wstool init ~/catkin_ws/src openag_brain_ros_indigo_deps_wet.rosinstall

# Install binary and Python dependencies for all packages.
# Walks workspace for `package.xml` files and looks up packages in rosdep
# sources list. Sources list for rosdep can be found here
# https://github.com/ros/rosdistro
# Installable sources are typically apt-get packages or pip packages.
# http://wiki.ros.org/rosdep
rosdep install --from-paths src --ignore-src --rosdistro indigo -y -r --os=debian:jessie

echo "All finished! Ready to build with catkin_make."
