#!/bin/bash
type pio > /dev/null 2>&1 && echo "pio is already installed"; exit
sudo apt-get install python-virtualenv
virtualenv ~/pio_env
source ~/pio_env/bin/activate
pip install platformio
sudo ln -s ~/pio_env/bin/pio /usr/local/bin/pio
