#!/usr/bin/env python
import argparse

from couchdb import Server

from openag_brain.commands import load_fixture

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Populate the database with "
    "objects from the designated fixture")
    parser.add_argument('fixture')
    args = parser.parse_args()
    server = Server()
    load_fixture(server, args.fixture)
