#!/usr/bin/env python
import os
import time
import rospkg
import atexit
import argparse
import requests
import subprocess
import multiprocessing as mp

from openag.couch import Server
from openag.categories import all_categories, default_categories
from openag.cli.config import config as cli_config
from openag.db_names import (
    SOFTWARE_MODULE, FIRMWARE_MODULE, ENVIRONMENTAL_DATA_POINT
)

from openag_brain import commands
from openag_brain.srv import SetCategories
from openag_brain.utils import resolve_fixtures

modules = None

@atexit.register
def kill_children():
    if modules is not None:
        modules.terminate()
        modules.wait()

def spawn_modules(screen=False):
    roslaunch_command = ["roslaunch", "openag_brain", "modules.launch"]
    if screen:
        roslaunch_command.append("--screen")
    return subprocess.Popen(roslaunch_command)

def run_categories_process(queue):
    """
    Start a ROS service that allows the user to changes the set of categories
    enabled in this run of the system. Whenever the service is called, it adds
    the new list of categories to the given queue.

    It is convenient to run this service in a new process on every restart
    because `rospy` assumes that a python process will never outlive its ROS
    core and that it will certainly never have to register itself with a series
    of different ROS cores over time, as we would like to do here.
    """
    def run_process():
        import rospy
        rospy.init_node("categories_service")
        def callback(req):
            queue.put(req.categories)
            return SetCategories._response_class(True, "OK")
        rospy.Service(
            "set_categories", SetCategories, callback
        )
        rospy.spin()
    p = mp.Process(target=run_process)
    p.start()
    return p

def main(api_server, db_server, fixtures, screen, categories):
    # Initialize the database
    print "Initializing the database"
    db_server = db_server or cli_config["local_server"]["url"]
    command = ["openag", "db", "init"]
    if db_server:
        command.extend(["--db_url", db_server])
    db_server = db_server or "http://localhost:5984"
    api_server = api_server or "http://localhost:5000"
    command.extend(["--api_url", api_server])
    if subprocess.call(command):
        raise RuntimeError("Failed to initialize database")
    server = Server(db_server)

    # Load the fixture
    for fixture_path in fixtures:
        print "Applying fixture {}".format(fixture_path)
        if subprocess.call(
            ["openag", "db", "load_fixture", fixture_path]
        ):
            raise RuntimeError("Failed to load fixture " + fixture_path)

    # Start the software modules
    print "Generating launch file"
    commands.update_launch(server, categories=categories)
    global modules
    print "Spawning software modules"
    modules = spawn_modules(screen)

    # Listen for calls to change the set of categories enabled
    categories_queue = mp.Queue(1)
    categories_process = run_categories_process(categories_queue)

    # Whenever the software or firmware module configuration changes, restart
    # the software modules
    software_db = server[SOFTWARE_MODULE]
    firmware_db = server[FIRMWARE_MODULE]
    edp_db = server[ENVIRONMENTAL_DATA_POINT]
    last_software_seq = software_db.changes(
        limit=1, descending=True
    ) ["last_seq"]
    last_firmware_seq = firmware_db.changes(
        limit=1, descending=True
    )["last_seq"]
    while True:
        time.sleep(5)
        software_changes = software_db.changes(since=last_software_seq)
        firmware_changes = firmware_db.changes(since=last_firmware_seq)
        last_software_seq = software_changes["last_seq"]
        last_firmware_seq = firmware_changes["last_seq"]
        if len(software_changes["results"]) or len(firmware_changes["results"]) or categories_queue.full():
            # Handle the categories service
            if categories_queue.full():
                categories = categories_queue.get_nowait()

            print "Module configuration changed; Restarting"
            modules.terminate()
            categories_process.terminate()
            categories_process.join()
            print "Generating launch file"
            commands.update_launch(server, categories=categories)
            modules.wait()
            print "Spawning software modules"
            modules = spawn_modules(screen)
            categories_process = run_categories_process(categories_queue)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description="""
Runs the entire software project. In particular, it initializes the
database (init_db), optionally applies a fixture to the database
(load_fixture), generates a roslaunch file for the software modules
(update_launch), runs the roslaunch file, and respawns if there is a change to
the configuration of the software modules
        """,
    )
    parser.add_argument(
        "-A", "--api_server", help="Address of the API from the api module"
    )
    parser.add_argument(
        "-D", "--db_server", help="Address of the database server"
    )
    parser.add_argument(
        '-f', '--fixture', help="Name of the fixture to apply to the database",
        default=[], nargs="+", dest='fixtures'
    )
    parser.add_argument(
        '-F', '--fixture_path',
        help="""
Path to a json fixture file to apply to the database. Specify the full path to
the fixture file. This flag is useful for loading fixtures not located in the
default fixtures directory.
        """,
        default=[], nargs="+", dest='fixture_paths'
    )
    parser.add_argument(
        "-c", "--categories", nargs='*', default=default_categories,
        choices=all_categories, help=""""
The categories of modules/inputs/outputs to be enabled in this run of the
system
""")
    parser.add_argument(
        "--screen", action="store_true",
        help="""
Passes the --screen flag to the roslaunch call, which forces all node output to
the screen. Useful for debugging.
""")
    vals = parser.parse_args()
    # Resolve named fixtures, then join named fixtures and path fixtures.
    fixture_paths = resolve_fixtures(vals.fixtures) + vals.fixture_paths
    main(
        api_server=vals.api_server, db_server=vals.db_server,
        fixtures=fixture_paths, screen=vals.screen, categories=vals.categories
    )
