#!/usr/bin/env python
import time
import atexit
import argparse
import requests
import subprocess

from couchdb import Server

from openag_brain import DbName, commands

modules = None

@atexit.register
def kill_children():
    if modules is not None:
        modules.terminate()
        modules.wait()

def main(database, hostname, fixture=None):
    # Install platformio
    print "Installing PlatformIO"
    subprocess.call(["rosrun", "openag_brain",  "install_pio"])

    # Initialize the database
    print "Initializing the database..."
    server = Server(database)
    commands.init_db(server, hostname)

    # Load the fixture
    if fixture:
        print "Applying fixture {}...".format(fixture)
        commands.load_fixture(server, args.fixture)

    # Start the software modules
    commands.update_launch(server)
    global modules
    modules = subprocess.Popen(["roslaunch", "openag_brain", "modules.launch"])

    # Flash the arduino
    commands.generate_firmware(server)
    subprocess.call(["rosrun", "openag_brain", "flash_arduino"])

    # Whenever the softwate module configuration changes, restart the software
    # modules
    # Whenever the firmware module configuration changes, reflash the arduino
    last_software_seq = requests.get(
        database + "/{db}/_changes".format(db=DbName.SOFTWARE_MODULE)
    ).json()['last_seq']
    last_firmware_seq = requests.get(
        database + "/{db}/_changes".format(db=DbName.FIRMWARE_MODULE)
    ).json()['last_seq']
    while True:
        time.sleep(2)
        software_changes = requests.get(
            database + "/{db}/_changes?last-event-id={last_seq}".format(
                db=DbName.SOFTWARE_MODULE, last_seq=last_software_seq
            )
        ).json()
        last_software_seq = software_changes['last_seq']
        if len(software_changes['results']):
            modules.terminate()
            commands.update_launch(server)
            modules.wait()
            modules = subprocess.Popen(["roslaunch", "openag_brain", "modules.launch"])
        firmware_changes = requests.get(
            database + "/{db}/_changes?last-event-id={last_seq}".format(
                db=DbName.FIRMWARE_MODULE, last_seq=last_firmware_seq
            )
        ).json()
        last_firmware_seq = firmware_changes['last_seq']
        if len(firmware_changes['results']):
            commands.generate_firmware(server)
            subprocess.call(["rosrun", "openag_brain", "flash_arduino"])

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description="Run the API and software modules for openag_brain",
    )
    parser.add_argument(
        "-D", "--database", help="Address of the database server",
        default="http://localhost:5984"
    )
    parser.add_argument(
        "-H", "--hostname", help="Hostame of the machine running this file",
        default="localhost"
    )
    parser.add_argument(
        '-f', '--fixture', help="Name of the fixture to apply to the database"
    )
    args = parser.parse_args()
    main(args.database, args.hostname, args.fixture)
