#!/usr/bin/env python
from couchdb import Server

from openag_brain.commands import update_launch

if __name__ == '__main__':
    # Open a connection to the CouchDB server
    server = Server()
    update_launch(server)
